### ISSUE TITLE
Issues #2

### ISSUE THREAD

**Issue by DokaRus** [roman-usov/frontend-project-46#3]
https://github.com/roman-usov/frontend-project-46/blob/72c69ffa5467dd9a2e8220fddce6267d27f39a89/bin/gendiff.js#L10

В скриптах сборки/CLI обычно завязываются на версию пакета

Т.е.

```
import pkg from '../package.json';

program
  .name('gendiff')
  .description('Compares two configuration files and shows a difference.')
  .version(pkg.version)
// and go on
```

Вообще, и имя с описанием тоже из package.json вытащить можно

-------------------

https://github.com/roman-usov/frontend-project-46/blob/72c69ffa5467dd9a2e8220fddce6267d27f39a89/index.js#L5-L8

Тут в `try/catch` стоит обернуть и вывод сообщения в случае ошибки сделать

-------------------

https://github.com/roman-usov/frontend-project-46/blob/72c69ffa5467dd9a2e8220fddce6267d27f39a89/src/genDiffForNestedObjs.js#L16-L25

Тут мне не очень нравятся повторяющиеся паттерны объекта и постоянная деструктуризация аккумулятора.
Т.е.  на возврате значения аккумулятор деструктуризуется и затем создаётся новый массив (с выделением памяти под него!), в который добавляется одно значение. Если надо просто добавить значение в аккумулятор - то стоит так и сделать (тем более, что функция рекурсивная - при работе с ней надо аккуратно подходить к использованию памяти)

```
if (isObject(originalValue) && isObject(changedValue)) {
  acc.push({
    [key]: {
      status: UNCHANGED,
      depth,
      children: iterate(originalValue, changedValue, depth + 1),
  });
  return acc;
}
```

-------------------

https://github.com/roman-usov/frontend-project-46/blob/72c69ffa5467dd9a2e8220fddce6267d27f39a89/src/utils.js#L16-L17

А почему б функцию не вынести, просто не экспортировать?
```
function objIterator(value, depth = 1) {
    if (!isObject(value)) {
      return `${value}`;
    }

    const indentSize = replacerCount * depth;
    const indentBeforeKey = indent(replacer, indentSize);
    const indentBeforeClosingParen = indent(replacer, indentSize - replacerCount);

    const lines = Object.entries(value).reduce(
      (prevStr, [key, val]) => `${prevStr}${indentBeforeKey}${key}: ${iterator(val, depth + 1)}\n`,
      '',
    );

    return `{\n${lines}${indentBeforeClosingParen}}`;
}

export function stringify(data, replacer = ' ', replacerCount = 1, startingDepth = 1) {
  return objIterator(data, startingDepth);
}
```

-------------------

Для парсеров я б ещё `try-catch` блоков добавил. На случай если при парсинге чего-то не так пошло, чтобы ошибка осмысленная была, а не "что-то в коде упало"

-------------------

https://github.com/roman-usov/frontend-project-46/blob/72c69ffa5467dd9a2e8220fddce6267d27f39a89/src/formatters/stylish.js#L4-L30

Не очень удобная с точки зрения читабельности функция. Вложенность стоило б уменьшить, может подумать ещё над рефакторингом. 
Что сходу видно
https://github.com/roman-usov/frontend-project-46/blob/72c69ffa5467dd9a2e8220fddce6267d27f39a89/src/formatters/stylish.js#L15-L22

Тут строка до двоеточия идентична - можно её вычислить и обозвать понятным именем
```
const keyStr = `${acc}${indentBefore}${details.status}${key}`

 if (details.children) {
        return `${keyStr}: {\n${iterate(
          details.children,
        )}${indentAfter}}\n`;
      }

      return `${keyStr}:${
        details.value === '' ? '' : ' '
// and go on
```

-------------------

Кстати, в [workflow ](https://github.com/roman-usov/frontend-project-46/blob/master/.github/workflows/project-check.yml)у тебя матрица версий не используется, можно немного лишнего повыкидывать

```
jobs:
  build:
    # The type of machine to run the job on
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under GitHub workspace
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
        # Step's name
      - name: Use Node.js 14.x
        # Configures the node version used on GitHub-hosted runners
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        # The Node.js version to configure
        with:
          node-version: 14.x
          cache: 'npm'
      - run: make install
      - run: make lint
      - run: make test
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v3.0.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
```

Субъективно, несколько излишним выглядит заведение makefile - в том же workflow вполне можно запускать npm скрипты напрямую (ты же на ранних шагах ставишь ноду) и чаще скрипты для запуска тестов, линта и т.п. описываются в скриптовой секции `package.json`

```
// package.json

scripts: {
  "test:lint": "eslint .",
  "test:unit": "jest",
  "test": "test:lint && test:unit"
}

// workflow

      - run: npm ci
      - run: npm test
// and go on

**Comment by roman-usov** [comment]
> В скриптах сборки/CLI обычно завязываются на версию пакета

Попробовал сделать так
`import pkg from '../package.json';`

Не знаю, что произошло. Сначала нормально читал свойства из  package.json. Потом начал выдавать ошибку. 

```
node:internal/errors:464 ErrorCaptureStackTrace(err); ^ TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json"
```
Погуглил, что, вроде, это поддерживается после 18 ноды и там нужно использовать `assert { 'json' }`

В итоге сработал только хак с require при работе с модулями. 

```
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const pkg = require('../package.json');
```

**Comment by roman-usov** [comment]
Пробую оборачивать в простые ошибки. Получаю странные результат. Кажется, что-то делаю не так. Не получается что-то похожее найти через google. 

В parsers добавляю обработку ошибки на случай, если не удалось запарсить файл. 

```
export default function parse(filePath) {
  try {
    const fileExt = getFileExtension(filePath);
    const fileContent = fs.readFileSync(getAbsolutePath(filePath));

    return parserController.getParser(fileExt)(fileContent);
  } catch (e) {
    throw new Error(`Can't read the file. ${e.message}.`);
  }
}
```
Вроде, выдает мою ошибку и stack trace под ней. Но смущает, что до этого печатает кусок кода, который и выбрасывает ошибку. 

```
file:///Users/romanusov/code/js_studies/frontend-project-46/src/parsers/parse.js:14
    throw new Error(`Can't read the file. ${e.message}.`);
          ^
```

Все вместе выглядит вот так

```
file:///Users/romanusov/code/js_studies/frontend-project-46/src/parsers/parse.js:14
    throw new Error(`Can't read the file. ${e.message}.`);
          ^

Error: Can't read the file. ENOENT: no such file or directory, open '/Users/romanusov/code/js_studies/frontend-project-46/src/__tests__/__fixtures__/changed-file.jsox'.
    at parse (file:///Users/romanusov/code/js_studies/frontend-project-46/src/parsers/parse.js:14:11)
    at genDiff (file:///Users/romanusov/code/js_studies/frontend-project-46/index.js:6:65)
    at Command.<anonymous> (file:///Users/romanusov/code/js_studies/frontend-project-46/bin/gendiff.js:20:17)
    at Command.listener [as _actionHandler] (/Users/romanusov/code/js_studies/frontend-project-46/node_modules/commander/lib/command.js:482:17)
    at /Users/romanusov/code/js_studies/frontend-project-46/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/Users/romanusov/code/js_studies/frontend-project-46/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/Users/romanusov/code/js_studies/frontend-project-46/node_modules/commander/lib/command.js:1283:27)
    at Command.parse (/Users/romanusov/code/js_studies/frontend-project-46/node_modules/commander/lib/command.js:909:10)
    at file:///Users/romanusov/code/js_studies/frontend-project-46/bin/gendiff.js:22:4
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)

```

Не пойму, где косячу.

**Comment by roman-usov** [comment]
>А почему б функцию не вынести, просто не экспортировать?

По идее, да, можно. Но тут внутренняя функция iterate опирается внутри на аргументы replacer и replaceCount, которые пришли в родительскую функцию и значения которых не меняются при рекурсии, и, вроде, каждый раз их прокидывать в iterate и не нужно. 

В уроках на hexlet они, как раз, такой паттерн давали в двух случаях. Первый я описал выше. А второй - когда в итераторе нужны какие-то доп. параметры, которые не поступают в родительскую функцию, но нужны для итерирования.

**Comment by roman-usov** [comment]
> Тут мне не очень нравятся повторяющиеся паттерны объекта и постоянная деструктуризация аккумулятора.
Т.е. на возврате значения аккумулятор деструктуризуется и затем создаётся новый массив (с выделением памяти под него!), в который добавляется одно значение. Если надо просто добавить значение в аккумулятор - то стоит так и сделать (тем более, что функция рекурсивная - при работе с ней надо аккуратно подходить к использованию памяти)


Да, уж, хорошее замечание. Я об этом не подумал. Реально, нет смысла плодить в памяти новые массивы, а пушить в существующий массив и потом перезаписывать значение в  acc. 

По поводу повторяющихся паттернов объектов, пока только следующее в голову пришло. Унифицировал структуру объекта для всех случаев. И за счет этого вынес создание объекта в отдельную функцию. И ее уже просто вызываю при генерации дерева. 

```javascript
function createDiffObj(key, status, depth, value, children = null) {
  return {
    [key]: {
      status,
      depth,
      value,
      children,
    },
  };
}
```

```javascript
export default function genDiffForNestedObjs(originalObj, changedObj) {
  function iterate(origObj, chObj, depth = 1) {
    const uniqueKeys = sortBy(Object.keys({ ...origObj, ...chObj }));

    return uniqueKeys.reduce((acc, key) => {
      const originalValue = origObj[key];
      const changedValue = chObj[key];

      if (isObject(originalValue) && isObject(changedValue)) {
        const children = iterate(originalValue, changedValue, depth + 1);
        acc.push(createDiffObj(key, UNCHANGED, depth, null, children));
        return acc;
      }

      if (isEqual(originalValue, changedValue)) {
        acc.push(createDiffObj(key, UNCHANGED, depth, originalValue));
        return acc;
      }

      if (has(origObj, key) && !has(chObj, key)) {
        acc.push(createDiffObj(key, REMOVED, depth, originalValue));
        return acc;
      }

      if (!has(origObj, key) && has(chObj, key)) {
        acc.push(createDiffObj(key, ADDED, depth, changedValue));
        return acc;
      }

      acc.push(createDiffObj(key, REMOVED, depth, originalValue));
      acc.push(createDiffObj(key, ADDED, depth, changedValue));
      return acc;
    }, []);
  }

  return iterate(originalObj, changedObj, 1);
}
```
Чёт мозгов не хватает на что-то более красивое.

**Comment by roman-usov** [comment]
> Не очень удобная с точки зрения читабельности функция. Вложенность стоило б уменьшить, может подумать ещё над рефакторингом.

Не знаю, в правильном ли направлении пошел, но попробовал вот так изменить. 

```javascript
function createObjPropertyString(key, space, val) {
  return `${key}:${space}${val}`;
}

function stylish(data) {
  function iterate(val) {
    return val.reduce((acc, element) => {
      const [key, details] = Object.entries(element).flat();

      const indentBefore = INDENT_CHAR.repeat(
        SPACES_PER_INDENT * details.depth - SPACES_FOR_CHANGE_INFO,
      );
      const indentAfter = INDENT_CHAR.repeat(SPACES_PER_INDENT * details.depth);

      const keyString = `${acc}${indentBefore}${details.status}${key}`;

      const spaceAfterColon = details.value === '' ? '' : ' ';

      let valueString;

      if (details.children) {
        const childrenString = iterate(details.children);
        valueString = `{\n${childrenString}${indentAfter}}\n`;

        return createObjPropertyString(keyString, spaceAfterColon, valueString);
      }

      valueString = `${stringify(
        details.value,
        INDENT_CHAR,
        SPACES_PER_INDENT,
        details.depth + 1,
      )}\n`;

      return createObjPropertyString(keyString, spaceAfterColon, valueString);
    }, '');
  }

  const lines = iterate(data);

  return `\n{\n${lines}}`;
}
```

**Comment by roman-usov** [comment]
> Кстати, в [workflow ](https://github.com/roman-usov/frontend-project-46/blob/master/.github/workflows/project-check.yml)у тебя матрица версий не используется, можно немного лишнего повыкидывать

Принял, упростил.

**Comment by roman-usov** [comment]
> Субъективно, несколько излишним выглядит заведение makefile - в том же workflow вполне можно запускать npm скрипты напрямую (ты же на ранних шагах ставишь ноду) и чаще скрипты для запуска тестов, линта и т.п. описываются в скриптовой секции

Завелось у меня только вот так
```
  "scripts": {
    "test:lint": "eslint .",
    "test:unit": "jest",
    "test": "npm run test:lint && npm run test:unit"
  },
```
make

```
test-coverage: npm run test:unit -- --coverage --coverageProvider=v8
```
По поводу make, на hexlet за него топят и просят использовать.

**Comment by DokaRus** [comment]
По package.json - можно средствами ноды прочитать файл и распарсить - этот подход точно не экспериментальный и должен надёжно работать
```
import fs from 'fs';
const pkg = JSON.parse(fs.readFileSync('../package.json'));
```

**Comment by DokaRus** [comment]
> Пробую оборачивать в простые ошибки. Например, в parse. Получаю странные результат. Кажется, что-то делаю не так. Не получается что-то похожее найти через google.
>
>В parsers добавляю обработку ошибки на случай, если не удалось запарсить файл.

_Неправильно ты, дядя Фёдор, будерброд ешь_

Гляди, ты **перехватил** ошибку, но вместо её обработки, **зарайзил новую ошибку** и программа/скрипт на этом аварийно завершает свою работу. В идеале, приложение должно быть устойчивым - на разламываться при внештатной ситуации. Есть разные способы этого добиться. К примеру, ты можешь при перехвате ошибки попробовать использовать какую-то дефолтную логику или вывести пользователю **сообщение** (не райзить ошибку!), и выйти из контекста выполнения текущей функции.
Т.е. что-то типа
```
export default function parse(filePath) {
  try {
    const fileExt = getFileExtension(filePath);
    const fileContent = fs.readFileSync(getAbsolutePath(filePath));

    return parserController.getParser(fileExt)(fileContent);
  } catch (e) {
    console.error(`Can't read the file. ${e.message}.`);
  }
}
```

**Comment by DokaRus** [comment]
>Не знаю, в правильном ли направлении пошел, но попробовал вот так изменить.

Ну вот тут я точно не вижу аргументов,, почему не вынести iterate как отдельную функцию :)

```
const spaceAfterColon = details.value === '' ? '' : ' ';
```
Может так?
```
const spaceAfterColon = !details.value ? '' : ' ';
```

**Comment by DokaRus** [comment]
> По поводу make, на hexlet за него топят и просят использовать.

Банда смузи-разработчиков :) Шутка, но...
Подобных подход может усложнить локальную разработку. Использование makefile норм, если у всех, кто работает с этим есть модный мак или линух. А вот если комп на винде, то придется ставить WSL или пакеты, реализующие функционал make утилиты. Причём в ридми владельцы реп об этом обычно не пишут и для закоренеллого виндоузятника это может быть неожиданной проблемой - чё-то не работает и неясно почему.

**Comment by roman-usov** [comment]
> > Пробую оборачивать в простые ошибки. Например, в parse. Получаю странные результат. Кажется, что-то делаю не так. Не получается что-то похожее найти через google.
> > В parsers добавляю обработку ошибки на случай, если не удалось запарсить файл.
> 
> _Неправильно ты, дядя Фёдор, будерброд ешь_
> 
> Гляди, ты **перехватил** ошибку, но вместо её обработки, **зарайзил новую ошибку** и программа/скрипт на этом аварийно завершает свою работу. В идеале, приложение должно быть устойчивым - на разламываться при внештатной ситуации. Есть разные способы этого добиться. К примеру, ты можешь при перехвате ошибки попробовать использовать какую-то дефолтную логику или вывести пользователю **сообщение** (не райзить ошибку!), и выйти из контекста выполнения текущей функции. Т.е. что-то типа
> 
> ```
> export default function parse(filePath) {
>   try {
>     const fileExt = getFileExtension(filePath);
>     const fileContent = fs.readFileSync(getAbsolutePath(filePath));
> 
>     return parserController.getParser(fileExt)(fileContent);
>   } catch (e) {
>     console.error(`Can't read the file. ${e.message}.`);
>   }
> }
> ```

 Переделал обработку ошибок. Вроде, получше, но все равно ощущение, что все не то))

```
❯ gendiff --format plain /Users/romanusov/code/js_studies/frontend-project-46/src/__tests__/__fixtures__/original-file.json src/__tests__/__fixtures__/changed-file.jso
Can't read the file. Error message: ENOENT: no such file or directory, open '/Users/romanusov/code/js_studies/frontend-project-46/src/__tests__/__fixtures__/changed-file.jso'.
Failed to generate the diff.
undefined

❯ gendiff --format plain /Users/romanusov/code/js_studies/frontend-project-46/src/__tests__/__fixtures__/original-file.json src/__tests__/__fixtures__/changed-file.txt
Can't parse the file of txt type.
Can't read the file. Error message: parserController.getParser(...) is not a function.
Failed to generate the diff.
undefined

❯ gendiff --format text  /Users/romanusov/code/js_studies/frontend-project-46/src/__tests__/__fixtures__/original-file.json src/__tests__/__fixtures__/changed-file.json
Can't format the output using the formatter of text type.
Failed to format the output.
undefined
```
Все равно автоматом идет возврат undefined. 
Как я понимаю, ошибочки всплывают из глубины кода наверх до самой верхнего обработчика. Получается что-то типа stack trace-a, объясняющего, что пошло не так. У меня самый верхний обработчик выбрасывает Failed to generate the diff. В ошибках с нахождением файла и форматом файла он отрабатывает. А когда подсовываешь не тот формат, не отрабатываем. 

Можно будет у тебя попросить аудиенции порефакторить это вместе?)

**Comment by roman-usov** [comment]
> > Не знаю, в правильном ли направлении пошел, но попробовал вот так изменить.
> 
> Ну вот тут я точно не вижу аргументов,, почему не вынести iterate как отдельную функцию :)
> 
> Плюс тернарник можно чуть проще описать
> 
> ```
> const spaceAfterColon = details.value === '' ? '' : ' ';
> ```
> 
> Может так?
> 
> ```
> const spaceAfterColon = !details.value ? '' : ' ';
> ```

Да, тут вынес без проблем. 

По поводу тернарника, не уверен. Т.к. тут условие именно на пустую строку. Если правильно понимаю, в твоем варианте условие сработает если значение, например, null. А null подменять не нужно.

**Comment by roman-usov** [comment]
> > По поводу make, на hexlet за него топят и просят использовать.
> 
> Банда смузи-разработчиков :) Шутка, но... Подобных подход может усложнить локальную разработку. Использование makefile норм, если у всех, кто работает с этим кодом есть модный мак или линух. А вот если комп на винде, то придется ставить WSL или пакеты, реализующие функционал make утилиты. Причём в ридми владельцы реп об этом обычно не пишут и для закоренеллого виндоузятника это может быть неожиданной проблемой - чё-то не работает и неясно почему.
> 
> Я не к тому, чтобы переделывать. Просто на будущее - скрипты необходимые для билда, тестирования стоит писать в npm-script секции и не завязываться на специфику определённой операционки для запуска этих скриптов

Ахах, смузи-разработчики)) Шикарно)) Представил - Бали, пляж, surf, mac, chill...
Да, почитал про установку make под Windows. Да, заморочки, конечно, есть. Действительно, если что-то из коробки работает под любой OS, то лучше и использовать.
